<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoworkingReservation.Domain\CoworkingReservation.Domain.csproj" />
    <ProjectReference Include="..\CoworkingReservation.Infrastructure\CoworkingReservation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
